import type { LandingStrings } from "../types";

export const en: LandingStrings = {
  nav: { problem: "The problem", sectors: "Sectors", cta: "Join the waitlist", pre: "Pre-launch" },
  hero: {
    tag1: "Montreal · Quebec",
    tag2: "Blue-collar seasonal hiring",
    h1a: "Hire", h1b: "reliable.", h1c: "Season after season.",
    lede: "Shift is the first digital infrastructure built for blue-collar seasonal hiring in Quebec. Circulate your workforce across seasons — without ever losing it.",
    emailLabel: "Email address", emailPh: "you@company.qc", join: "Join →",
    counter: "127 companies on the list · First access May 2026",
    cardLabel: "Proposed shift", cardLoc: "Outremont · Mon. 8 AM–4 PM",
    worker: "Marc Tremblay", workerSub: "3 seasons · Agriculture, Landscaping",
    confirm: "Confirm · $200", decline: "Decline",
  },
  problem: {
    eyebrow: "§ 01 — The problem",
    h2: "Seasonal hiring still runs on word of mouth. In the 21st century.",
    items: [
      { tag: "For employers",  title: "Kijiji, or nothing.", body: "40 unqualified replies, or zero. No way to find last year's best workers. Every spring starts from scratch." },
      { tag: "For workers",    title: "The cousin, Facebook, luck.", body: "No way to build a verifiable work history. Gaps between seasons. Invisible to employers outside personal networks." },
      { tag: "For suppliers",  title: "We lose our crews every winter.", body: "A crew trained May to October. In November they leave for the competition. No mechanism to lend them and get them back in spring." },
    ],
    insightLabel: "The core insight",
    insight: "Shift is not a job board. It is infrastructure that", insightHi: "circulates", insight2: "crews across complementary seasons — so the worker never experiences an employment gap.",
  },
  sectors: {
    eyebrow: "§ 02 — Circulation",
    h2: "Seasons that complement — not overlap.",
    lede: "Supplier and employer seasons are designed to fit together. This is the core insight behind the circulation model.",
    legendA: "Supplier's active season",
    legendB: "Receives the workers",
    legendBlank: "Available to circulate",
  },
  why: {
    eyebrow: "§ 03 — Why Quebec, why now",
    h2: "Right market. Right moment. Right language.",
    lede: "Quebec has the exact combination of conditions that makes it the ideal first market for Shift.",
    stats: [
      { v: "10K+",   l: "Missing workers",       s: "QC construction over 10 yrs" },
      { v: "6+",     l: "Seasonal sectors",      s: "May to March, complementary" },
      { v: "0",      l: "Digital infra exists",  s: "Specifically for blue-collar" },
      { v: "< $15",  l: "Infra cost / month",    s: "MVP — Vercel + Railway" },
    ],
    vs: [
      { title: "Why not Indeed?", body: "Built for white-collar. Blue-collar workers don't have a resume. Indeed treats a landscaper like an accountant." },
      { title: "Why not Kijiji?", body: "No verification. No reliability signal. No trust. 40 unqualified replies per post — or zero." },
    ],
  },
  waitlist: {
    eyebrow: "§ 04 — Join us",
    h2a: "Be among the", h2hi: "first 50", h2b: "employers.",
    lede: "First access in spring 2026. First 50 postings free. No card required.",
    onList: "On the list", market: "First market", opens: "Opens", marketV: "MTL", opensV: "May",
    youAre: "You are…",
    roles: [
      { id: "companyA", label: "Supplier",  hint: "Company A" },
      { id: "companyB", label: "Employer",  hint: "Company B" },
      { id: "worker",   label: "Worker",    hint: "Worker" },
    ],
    company: "Company", companyPh: "Boucher Landscaping Inc.",
    email: "Email", emailPh: "you@company.qc",
    phone: "Phone", phonePh: "(514) 555-0123", phoneHint: "We'll text you the code.",
    sectorLabel: "Primary sector",
    submit: "Join the waitlist →",
    microcopy: "EN/FR · No spam · Unsubscribe anytime",
    thanksStamp: "THANKS.", thanksH: "You're on the list.",
    thanksBody: "We'll SMS you the day Shift opens in Montreal. First come, first served.",
    thanksTo: "Confirmation sent to",
  },
  footer: {
    tagline: "The first digital infrastructure for blue-collar seasonal hiring in Quebec. Built to circulate crews — not replace them.",
    product: "Product", company: "Company", legal: "Legal · QC",
    productLinks: ["For employers", "For suppliers", "For workers", "Pricing · 15%"],
    companyLinks: ["About", "Manifesto", "Press · contact", "Investors"],
    addr: ["Shift Marketplace Inc.", "1234 rue Saint-Laurent", "Montréal, QC · H2X 2T3"],
    legalLinks: ["Privacy · Law 25", "Terms"],
    copy: "© 2026 Shift Marketplace Inc.",
    built: "Built in Montreal · Stripe Connect · Twilio · Vercel",
  },
};
