import type { LandingStrings } from "../types";

export const en: LandingStrings = {
  nav: { problem: "The problem", sectors: "Sectors", cta: "Join the waitlist", pre: "Pre-launch" },
  hero: {
    tag1: "Canada",
    tag2: "Blue-collar seasonal hiring",
    h1a: "Hire", h1b: "reliable.", h1c: "Season after season.",
    lede: "Shift is the first digital infrastructure built for blue-collar seasonal hiring in Quebec. Circulate your workforce across seasons without ever losing it.",
    emailLabel: "Email address", emailPh: "you@company.qc", join: "Join →",
    counter: "127 companies on the list · First access May 2026",
    microcopy: "EN/FR · No spam · Unsubscribe anytime",
    thanksStamp: "THANKS.", thanksH: "You're on the list.",
    thanksBody: "We'll SMS you the day Shift opens in Montreal. First come, first served.",
    thanksTo: "Confirmation sent to",
    bookCall: "Book a call →",
  },
  problem: {
    headline: "Keep the majority of your employees for the next season.",
    headlineHi: "Recycle your workforce.",
    cards: [
      { title: "It's reliable.", body: "Your best workers come back to you automatically. No more starting from scratch every spring." },
      { title: "Mind free.", body: "Stop worrying about who's coming back. Focus on running your business, not finding your crew." },
      { title: "You're profitable.", body: "Less onboarding. Less training. More output. Higher margins, season after season." },
    ],
    pipeline: "A connecting pipeline between companies.",
    sub: "Now you can run your business without worrying about workforce. We help you.",
  },
  sectors: {
    eyebrow: "§ 02 — How it works",
    h2: "Shift once. Hire for life.",
    steps: [
      { title: "Post your season.", body: "Tell Shift your sector, region, dates, and crew size. Five minutes to set up — zero recruiter fees." },
      { title: "Workers shift in.", body: "Shift surfaces verified workers from complementary sectors whose off-season lines up with your peak." },
      { title: "They arrive ready.", body: "Every worker comes pre-screened — skills, availability, and sector experience confirmed before day one." },
      { title: "Shift pays your crew.", body: "No payroll setup on your end. Shift handles worker payments directly. You get one clean invoice per season." },
      { title: "Crew follows the work.", body: "When your season ends, your workers shift to the next company in the network — and come back to you next year, ready." },
      { title: "Keep the shift alive.", body: "Flag your best crew. Shift locks them in for your next season automatically. No reposting. No retraining." },
    ],
  },
  pricing: {
    eyebrow: "§ — Pricing",
    h2: "The more we grow, the less you pay.",
    lede: "Employer fees decrease as the Shift network scales. Early adopters lock in the best rate.",
    rateLabel: "employer fee",
    atWorkers: "at",
    inNetwork: "workers in the network",
    dragHint: "drag to explore",
    thresholdDrop: "−0.1%",
    lendTitle: "You earn 0.75% back.",
    lendRate: "0.75%",
    lendBody: "Every week your workers are placed at another company, you receive {{rate}} of their salary — automatically. Your off-season generates passive income.",
    workerTitle: "Workers always pay $0.",
    workerBody: "Free to join, free to move between companies. The network grows when workers trust it.",
    disclaimer: "Rates apply to active placement periods only. No subscription. No setup costs.",
  },
  faq: {
    eyebrow: "§ 03 — FAQ",
    h2: "Frequently asked.",
    items: [
      { q: "What is Shift, exactly?", a: "Shift is a digital marketplace that circulates blue-collar workers across complementary seasonal sectors. A landscaper works summers for you, winters for a snow removal company — and comes back to you next spring. One verified profile. Year-round income. Zero recruiting." },
      { q: "Who is Shift built for?", a: "Employers who run seasonal crews — landscaping, construction, ski, agriculture, moving — and workers who want stable year-round income without hunting for jobs every season." },
      { q: "How does payment work?", a: "Shift handles all payroll. You receive one clean invoice per season. Workers are paid weekly through Shift. No payroll setup, no wire transfers, no headaches." },
      { q: "How are workers verified?", a: "Every worker completes identity verification, sector-specific skills confirmation, and past employment checks. Only verified profiles appear in your search results." },
      { q: "What does Shift cost?", a: "Free for workers. Employers pay a service fee starting at 4.99% per placement — applied only during active periods when a worker is placed at your company. The fee decreases as the Shift network grows. No subscription. No setup cost." },
    ],
  },
  contact: {
    eyebrow: "§ 04 — Contact",
    h2: "Let's talk.",
    body: "Questions, partnerships, press — we're reachable.",
    email: "hello@shift.work",
    press: "press@shift.work",
  },
  footer: {
    tagline: "The first digital infrastructure for blue-collar seasonal hiring in Quebec. Built to circulate crews — not replace them.",
    product: "Product", company: "Company", legal: "Legal · QC",
    productLinks: ["For employers", "For suppliers", "For workers", "Pricing · 4.99%"],
    companyLinks: ["About", "Manifesto", "Press · contact", "Investors"],
    addr: ["Shift Marketplace Inc.", "1234 rue Saint-Laurent", "Montréal, QC · H2X 2T3"],
    legalLinks: ["Privacy · Law 25", "Terms"],
    copy: "© 2026 Shift Marketplace Inc.",
    built: "Built in Montreal · Stripe Connect · Twilio · Vercel",
  },
};
