import type { LandingStrings } from "../types";

export const fr: LandingStrings = {
  nav: { problem: "Le problème", sectors: "Secteurs", cta: "Rejoindre la liste", pre: "Pré-lancement" },
  hero: {
    tag1: "Canada",
    tag2: "Embauche saisonnière col-bleu",
    h1a: "Embauchez", h1b: "fiable.", h1c: "Saison après saison.",
    lede: "Shift est la première infrastructure numérique pour l'embauche saisonnière col-bleu au Québec. Faites circuler vos travailleurs entre les saisons sans jamais les perdre.",
    emailLabel: "Adresse courriel", emailPh: "vous@entreprise.qc", join: "Rejoindre →",
    counter: "127 entreprises sur la liste · Premier accès en mai 2026",
    microcopy: "FR/EN · Aucun spam · Vous pouvez vous désinscrire en tout temps",
    thanksStamp: "MERCI.", thanksH: "Vous êtes sur la liste.",
    thanksBody: "On vous contacte par SMS dès que Shift ouvre à Montréal. Premier arrivé, premier servi.",
    thanksTo: "Confirmation envoyée à",
    bookCall: "Réserver un appel →",
  },
  problem: {
    headline: "Gardez la majorité de vos employés pour la prochaine saison.",
    headlineHi: "Recyclez votre main-d'œuvre.",
    cards: [
      { title: "C'est fiable.", body: "Vos meilleurs travailleurs reviennent automatiquement. Fini de repartir à zéro chaque printemps." },
      { title: "L'esprit libre.", body: "Arrêtez de vous inquiéter de qui revient. Concentrez-vous sur la gestion, pas sur le recrutement." },
      { title: "Vous êtes rentable.", body: "Moins d'intégration. Moins de formation. Plus de production. Des marges plus élevées, saison après saison." },
    ],
    pipeline: "Un pipeline de connexion entre entreprises.",
    sub: "Gérez votre entreprise sans vous inquiéter de la main-d'œuvre. Nous vous aidons.",
  },
  sectors: {
    eyebrow: "§ 02 — Comment ça marche",
    h2: "Un seul Shift. Une équipe pour toujours.",
    steps: [
      { title: "Publiez votre saison.", body: "Indiquez votre secteur, région, dates et taille d'équipe. Cinq minutes pour démarrer — sans frais de recrutement." },
      { title: "Les travailleurs se Shiftent.", body: "Shift identifie des travailleurs vérifiés dont la basse saison correspond exactement à votre haute saison." },
      { title: "Ils arrivent prêts.", body: "Chaque travailleur arrive pré-sélectionné — compétences, disponibilité et expérience confirmées avant le jour un." },
      { title: "Shift paie votre équipe.", body: "Zéro configuration de paie de votre côté. Shift gère les paiements des travailleurs directement. Une seule facture par saison." },
      { title: "L'équipe suit le travail.", body: "Quand votre saison se termine, vos travailleurs se Shiftent vers la prochaine entreprise du réseau — et reviennent chez vous l'an prochain." },
      { title: "Gardez le Shift actif.", body: "Marquez vos meilleurs. Shift les réserve pour votre prochaine saison automatiquement. Zéro repostage. Zéro réentraînement." },
    ],
  },
  pricing: {
    eyebrow: "§ — Tarification",
    h2: "Plus on grandit, moins vous payez.",
    lede: "Les frais employeur diminuent à mesure que le réseau Shift prend de l'ampleur. Les premiers adoptants obtiennent le meilleur taux.",
    rateLabel: "frais employeur",
    atWorkers: "à",
    inNetwork: "travailleurs dans le réseau",
    dragHint: "glisser pour explorer",
    thresholdDrop: "−0,1 %",
    lendTitle: "Vous récupérez 0,75 %.",
    lendRate: "0,75 %",
    lendBody: "Chaque semaine que vos travailleurs sont placés chez une autre entreprise, vous recevez {{rate}} de leur salaire — automatiquement. Votre basse saison génère un revenu passif.",
    workerTitle: "Les travailleurs paient toujours 0 $.",
    workerBody: "Gratuit pour rejoindre et pour changer d'entreprise. Le réseau grandit quand les travailleurs lui font confiance.",
    disclaimer: "Les taux s'appliquent aux périodes de placement actives seulement. Aucun abonnement. Aucun frais de démarrage.",
  },
  faq: {
    eyebrow: "§ 03 — FAQ",
    h2: "Questions fréquentes.",
    items: [
      { q: "C'est quoi Shift, exactement?", a: "Shift est un marché numérique qui fait circuler les travailleurs col-bleu entre des secteurs saisonniers complémentaires. Un paysagiste travaille pour vous l'été, pour une entreprise de déneigement l'hiver — et revient chez vous le printemps suivant. Un profil vérifié. Un revenu annuel stable. Zéro recrutement." },
      { q: "Pour qui est Shift?", a: "Les employeurs qui gèrent des équipes saisonnières — paysagement, construction, ski, agriculture, déménagement — et les travailleurs qui veulent un revenu stable à l'année sans chercher de contrats chaque saison." },
      { q: "Comment fonctionnent les paiements?", a: "Shift gère toute la paie. Vous recevez une seule facture par saison. Les travailleurs sont payés chaque semaine via Shift. Aucune configuration de paie, aucun virement, aucun casse-tête." },
      { q: "Comment les travailleurs sont-ils vérifiés?", a: "Chaque travailleur complète une vérification d'identité, une confirmation de compétences sectorielles et une validation de ses emplois précédents. Seuls les profils vérifiés apparaissent dans vos résultats." },
      { q: "Combien coûte Shift?", a: "Gratuit pour les travailleurs. Les employeurs paient des frais de service à partir de 4,99 % par placement — applicables uniquement pendant les périodes actives où un travailleur est chez votre entreprise. Les frais diminuent à mesure que le réseau Shift grandit. Aucun abonnement. Aucun frais de démarrage." },
    ],
  },
  contact: {
    eyebrow: "§ 04 — Contact",
    h2: "Parlons-en.",
    body: "Questions, partenariats, presse — nous sommes joignables.",
    email: "hello@shift.work",
    press: "presse@shift.work",
  },
  footer: {
    tagline: "La première infrastructure numérique pour l'embauche saisonnière col-bleu au Québec. Bâtie pour faire circuler les équipes — pas pour les remplacer.",
    product: "Produit", company: "Entreprise", legal: "Légal · QC",
    productLinks: ["Pour les employeurs", "Pour les fournisseurs", "Pour les travailleurs", "Tarifs · 4,99 %"],
    companyLinks: ["À propos", "Manifeste", "Contact · presse", "Investisseurs"],
    addr: ["Shift Marketplace Inc.", "1234 rue Saint-Laurent", "Montréal, QC · H2X 2T3"],
    legalLinks: ["Confidentialité · Loi 25", "Conditions"],
    copy: "© 2026 Shift Marketplace Inc.",
    built: "Bâti à Montréal · Stripe Connect · Twilio · Vercel",
  },
};
